var zophieRoutes = {
    "/":{
        "redirectTo":"/home"
    },
    "/home":{
        "url":"templates/home.html"
    },
    "/ask":{
        "url":"templates/ask.html"
    },
    "/ask/q=:query":{
        "url":"templates/query.html"
    },
    "/answer":{
        "url":"templates/answer.html",
        "reqlogin":true
    },
    "/addcontent":{
        "url":"templates/addcontent.html",
        "reqlogin":true
    },
    "/visualize":{
        "url":"templates/visualize.html"
    },
    "/about":{
        "url":"templates/about.html"
    },
    "/login":{
        "url":"templates/login.html"
    },
    "/register":{
        "url":"templates/register.html"
    },
    "/mypage":{
        "url":"templates/mypage.html",
        "reqlogin":true
    },
    "/logout":{
        "url":"templates/logout.html",
        "reqlogin":true
    },
    "/reqlogin":{
        "url":"templates/reqlogin.html"
    },
    "/wait":{
        "url":"templates/wait.html"
    },
    "/login/:authprovider":{
        "template":"",
        "controller":"AuthProviderController"
    }
}
